config-version: 5

#  @      @@@  @@@@@ @   @  @@@  @   @  @@@  @@@@@            @   @  @@@  @@@@  @@@@@ @@@@  @   @
#  @     @   @    @   @ @  @     @   @ @   @   @              @@ @@ @   @ @   @ @     @   @ @@  @
#  @     @@@@@   @     @   @     @@@@@ @@@@@   @      @@@@    @ @ @ @   @ @   @ @@@@  @@@@  @ @ @
#  @     @   @  @      @   @     @   @ @   @   @              @   @ @   @ @   @ @     @  @  @  @@
#  @@@@@ @   @ @@@@@   @    @@@  @   @ @   @   @              @   @  @@@  @@@@  @@@@@ @   @ @   @

options:
  language: English # Available: English, Russian, Ukrainian
  enable-logging: true # Enables logging to console.
  default: local # Chat that will be used by default
  save-internal-chats: true # Saves internal chats (or in other words chats, that included inside plugin).
  broadcast-cooldown: 70 # Cooldown in seconds. Used for guys cannot to spam with broadcasts
  chat-default-cooldown: 1 # Cooldown in seconds. Needed for remove spam. But, in every internal chat (global.yml etc.) uses their own cooldown

  # Enables some experiments like .json for chats or databases for mutes.
  experiments:
    jsonForChats: false
    databasesForMute: false

chats:
  global:
    template: "global.yml" # Template for global chat. You can use formats like JSON (WIP)
    prefix: "!" # Prefix for use global chat. By default, and most popular — "!".
    radius: -1 # If -1 or 0 — global.
  local:
    template: "local.yml" # Template for local chat.
    prefix: "" # Not set cause isn't need.
    radius: 100
  whisper:
    template: "whisper.yml"
    prefix: ["*", "_", "~"] # Supports aliases
    radius: 10
    perm: "" # If not set or just empty, will allow everyone to use this chat
  # Example chat with perms - Admin chat.
  #admin:
  #  template: "admin.yml"
  #  prefix: [":", "^"]
  #  perm: "lazychat.admin" # Able for set perm for chat. If not set, perm will be = none.
    # If player do not have perm — He cannot read and send messages in this chat. If he tries — in chat will send only text with prefix that DO NOT work.
  # Example chat - Business chat.
  #business:
  #  template: "business.json"
  #  prefix: ["$", ";"]
  #  radius: -1

blacklist:
  chat:
    minimessage: false # Disables able for players for use minimessage. By default, set to false or Minimessage can be used.
    gradients: false # Disables able for players for use gradients. By default, gradients enabled (or in other words on false).
    tags: # Disables custom (and not only) tags.
      - newline
      - obf
      - hover
      - lang
      - tr
      - translate
      - font
      - selector
      - score
      - nbt
      - sprite
      - click
  signs: false # Disables able for players for use MiniMessage on signs. By default, enabled (or in other words on false).