name: LazyChat
version: '0.3'
main: lazy.dev.lazyChat.LazyChat
api-version: '1.21'
authors: [ LazyCato0o ]
description: Plugin which improves chat system and adds support MiniMessage formating
website: https://github.com/LazyCat0/LazyChat-MC-plugin
permissions:
  l-chat.reload:
    description: Allow to reload LazyChat config
    default: op
commands:
  l-chat-rl:
    description: Reloads an a config for LazyChat.
    usage: /<command>
    permission: l-chat.reload